nome = str(input('Digite seu nome completo: ')).strip()
letras = len(nome) - nome.count(' ')
print('Analisando seu nome....')
print(f'Seu nome em maiúsculas é {nome.upper()}')
print(f'Seu nome em minúsculas é {nome.lower()}')
print(f'seu nome tem ao todo {letras} letras')
primeiro_nome = nome.find(' ')
separa = nome.split()
print(f'Seu primeiro nome é {separa[0]} e tem {primeiro_nome} letras')